# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibe-zsh" do
  name "vibe-zsh"
  desc "Transform natural language into shell commands using AI"
  homepage "https://github.com/skymoore/vibe-zsh"
  version "0.2.0-beta.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibe-zsh"

  on_macos do
    on_intel do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-darwin-amd64.tar.gz"
      sha256 "46f446f9cd31a84186c8408599221b52cdcbc3755643271cd98b7650354632db"
    end
    on_arm do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-darwin-arm64.tar.gz"
      sha256 "6b2711a50228dded09804d286749ce4be3efab8ca973a91676cd48c24937980e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-linux-amd64.tar.gz"
      sha256 "aa55b23cd6b1ad941519bb0928521d49123690d11bb863ed6feb683a72b4bb8c"
    end
    on_arm do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-linux-arm64.tar.gz"
      sha256 "525209b1a950a5df310454a31876e92108e5ccf7f3f193ddb80343069f83b90d"
    end
  end

  caveats do
    "vibe has been installed to:"
    "  #{staged_path}"
    ""
    "To activate vibe, add the following to your ~/.zshrc:"
    ""
    "  export PATH=\"#{staged_path}:$PATH\""
    "  source \"#{staged_path}/vibe.plugin.zsh\""
    "  fpath=(#{staged_path} $fpath)"
    ""
    "Then reload your shell:"
    "  source ~/.zshrc"
    ""
    "Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):"
    "  export VIBE_API_URL=\"http://localhost:11434/v1\""
    "  export VIBE_MODEL=\"llama3:8b\""
    ""
    "Use Ctrl+G to transform natural language into commands!"
  end

  # No zap stanza required
end
