# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibe-zsh" do
  name "vibe-zsh"
  desc "Transform natural language into shell commands using AI"
  homepage "https://github.com/skymoore/vibe-zsh"
  version "0.2.1-beta.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibe-zsh"
  depends_on formula: [
      "zsh",
    ]

  on_macos do
    on_intel do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-darwin-amd64.tar.gz"
      sha256 "6274a134f8269b2bbece68b085640dcfe1f8fb147665223f996194f48d152cd8"
    end
    on_arm do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-darwin-arm64.tar.gz"
      sha256 "eb44b47e0c88f2030cbe482f0eea228e31d075fcc5d8c0abec37266dfbac7114"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-linux-amd64.tar.gz"
      sha256 "fe989974d0690a3d99e6de2d4f111f988e66dbcaf7fb5632f6d761b290d27888"
    end
    on_arm do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-linux-arm64.tar.gz"
      sha256 "48cfe4541f1127dfdb7df2d1a1f943441af429c1bc993e168d1bafad4ad0ef06"
    end
  end

  caveats do
    "vibe has been installed to:"
    "  #{staged_path}"
    ""
    "To activate vibe, add the following to your ~/.zshrc:"
    ""
    "  export PATH=\"#{staged_path}/bin:$PATH\""
    "  source \"#{staged_path}/vibe.plugin.zsh\""
    "  fpath=(#{staged_path} $fpath)"
    ""
    "Then reload your shell:"
    "  source ~/.zshrc"
    ""
    "Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):"
    "  export VIBE_API_URL=\"http://localhost:11434/v1\""
    "  export VIBE_MODEL=\"llama3:8b\""
    ""
    "Use Ctrl+G to transform natural language into commands!"
  end

  # No zap stanza required
end
