# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibe-zsh" do
  name "vibe-zsh"
  desc "Transform natural language into shell commands using AI"
  homepage "https://github.com/skymoore/vibe-zsh"
  version "0.2.0-beta.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibe-zsh"

  on_macos do
    on_intel do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-darwin-amd64.tar.gz"
      sha256 "bc02f04cffb7938a6a2df7f9b9e472ca36cbe42796f2aeb81b960729fd6057a9"
    end
    on_arm do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-darwin-arm64.tar.gz"
      sha256 "e35fb2f50c45754109e8b7c74918d7d1ee32844b421c50475e320ceba48e0724"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-linux-amd64.tar.gz"
      sha256 "9a0be3c4a00fc6e3f88059cb189bd0fb765820b45bf55799058c913c54750ccb"
    end
    on_arm do
      url "https://github.com/skymoore/vibe-zsh/releases/download/v#{version}/vibe-zsh-#{version}-linux-arm64.tar.gz"
      sha256 "e9e92e455c21e1cb03fe179efa1f2e2d4fa5a078939ff0f20fdd8d8b44d4160f"
    end
  end

  caveats do
    "vibe has been installed to:"
    "  #{staged_path}"
    ""
    "To activate vibe, add the following to your ~/.zshrc:"
    ""
    "  export PATH=\"#{staged_path}:$PATH\""
    "  source \"#{staged_path}/vibe.plugin.zsh\""
    "  fpath=(#{staged_path} $fpath)"
    ""
    "Then reload your shell:"
    "  source ~/.zshrc"
    ""
    "Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):"
    "  export VIBE_API_URL=\"http://localhost:11434/v1\""
    "  export VIBE_MODEL=\"llama3:8b\""
    ""
    "Use Ctrl+G to transform natural language into commands!"
  end

  # No zap stanza required
end
