# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vibe < Formula
  desc "Transform natural language into shell commands using AI"
  homepage "https://github.com/skymoore/vibe-zsh"
  version "0.2.0-beta.2"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.2/vibe-zsh-0.2.0-beta.2-darwin-amd64.tar.gz"
      sha256 "f72c665a44e490b04f813ed08d451c8dcf88a2177414992b53ddd83159bdf53e"

      def install
        bin.install "vibe-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch}" => "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.2/vibe-zsh-0.2.0-beta.2-darwin-arm64.tar.gz"
      sha256 "32f9221cd427e54de65f8cb7d42cdfc1bb88b9f173a05223ab841c71b5f0fabd"

      def install
        bin.install "vibe-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch}" => "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.2/vibe-zsh-0.2.0-beta.2-linux-amd64.tar.gz"
      sha256 "b3a20d14daf4730790c245e190c5d3601e37888696a06eddc2705fcdfd9b89c6"
      def install
        bin.install "vibe-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch}" => "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.2/vibe-zsh-0.2.0-beta.2-linux-arm64.tar.gz"
      sha256 "91a2a6ad8c6a0fe7943308cbd4a3e621f392477af1ade02ce4daabb737f49e96"
      def install
        bin.install "vibe-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch}" => "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
  end

  def caveats
    <<~EOS
      To activate vibe, add the following line to your ~/.zshrc file:

        source "$(brew --prefix)/opt/vibe/libexec/vibe.plugin.zsh"

      Then, restart your shell or run:
        source ~/.zshrc

      Zsh completions have been installed automatically.

      Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):
        export VIBE_API_URL="http://localhost:11434/v1"
        export VIBE_MODEL="llama3:8b"

      Use Ctrl+G to transform natural language into commands!
    EOS
  end
end
