# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VibeZsh < Formula
  desc "Transform natural language into shell commands using AI"
  homepage "https://github.com/skymoore/vibe-zsh"
  version "0.2.0-beta.4"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.4/vibe-zsh-0.2.0-beta.4-darwin-amd64.tar.gz"
      sha256 "b1aae8278d1a1af45b2ad52fbec777f507dc52fddca611249624455990d05a71"

      def install
        bin.install "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.4/vibe-zsh-0.2.0-beta.4-darwin-arm64.tar.gz"
      sha256 "30e654d0c9e1c8f39a3c352f3499eeca9491b2fe8b410bd8c39e742f5a7ad23e"

      def install
        bin.install "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.4/vibe-zsh-0.2.0-beta.4-linux-amd64.tar.gz"
      sha256 "534afdb8ea439120ea7a943ea12c613b2a54f23d606bc74078929700213d892f"
      def install
        bin.install "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skymoore/vibe-zsh/releases/download/v0.2.0-beta.4/vibe-zsh-0.2.0-beta.4-linux-arm64.tar.gz"
      sha256 "032e4502cb58f494b55a835dc1383774a1f3ec451bdd96dc781500713e0f440c"
      def install
        bin.install "vibe"
        libexec.install "vibe.plugin.zsh"
        zsh_completion.install "_vibe"
      end
    end
  end

  def caveats
    <<~EOS
      To activate vibe, add the following line to your ~/.zshrc file:

        source "$(brew --prefix)/opt/vibe/libexec/vibe.plugin.zsh"

      Then, restart your shell or run:
        source ~/.zshrc

      Zsh completions have been installed automatically.

      Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):
        export VIBE_API_URL="http://localhost:11434/v1"
        export VIBE_MODEL="llama3:8b"

      Use Ctrl+G to transform natural language into commands!
    EOS
  end
end
